Delete http://localhost:3001/api/blogs/65787affdc48cb1dfcce7f7e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkV2aWwiLCJpZCI6IjY1Nzg3N2M4MTZkMjBmOGI1YWE3ZWQ3YiIsImlhdCI6MTcwMjM5NDE0MywiZXhwIjoxNzAyMzk3NzQzfQ.nKZaYFo2HnA9YzKVWvLos9IOeBBazVpe5QI7MwWb4dM